# Generated by Django 2.2.2 on 2019-06-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='picture')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('pics', models.ImageField(upload_to='picture')),
            ],
        ),
    ]
