# Generated by Django 2.2.2 on 2019-06-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField()),
                ('body', models.TextField()),
                ('pic', models.ImageField(upload_to='picture')),
            ],
        ),
    ]
